---
 plugin: aws_ec2
 regions:
  - us-east-2
 hostnames:
  - ip-address
 keyed_groups:
  - key: tags.Name
    prefix: tag_Name

 #Task block
#- name: Install telnet
# ansible.builtin.package:
#   name: telnet
#   state: present
                       #ansible-playbook -i /aws_ec2.yaml
                    
                                 