# ansible-playbook 
---
- name: Add IAM users
  hosts: localhost
  tasks:
  - name: Create two new IAM users with API keys
    community.aws.iam:
     iam_type: user
     name: "{{ item }}"
     state: present
     password: "pass12345dfhahjkadDFASDFASFASDFASDF342432@!!#!@#!@#!!"
     access_key_state: create
    loop:
     - user1
     - user2
  - name: Create new group DevOps
    community.aws.iam:
     iam_type: group
     name: "{{ item }}"
     state: present
    loop:
     - DevOps
    register: new_groups  
  