# ansible-playbook aws_iam.yaml
---
- name: Add IAM users
  hosts: localhost
  tasks:
  - name: Create two new IAM users with API keys
    community.aws.iam:
     iam_type: user
     name: "{{ item }}"
     state: present
     password: "pass12345!"
     access_key_state: create
    loop:
     - user1
     - user2
    
